version: '2'


services:
  janus-gateway:
    image: daocloud.io/youyaochi/janus 
    container_name: janus-gateway
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./janus/janus.log:/var/log/janus.log
      - ./cert:/opt/janus/share/janus/certs/
    ports:
      - 8989:8989
    network_mode: "host"

